
---
- name: vCenterAnsible
  hosts: localhost
  remote_user: mtaneja
  environment:
    env_user: administrator@vsphere.local
    env_password: Admin!23
    env_host: 10.161.67.145
    env_port: 443

  roles:
      - datacenter
      - cluster
      - resourcepool
